project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Elijah Meyer"

  page-footer:
    left: "&copy; Copyright 2023, Elijah Meyer"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#2af0f7" # Teal
  navbar:
    background: "#2af0f7" # Teal
    foreground: "light"
    pinned: true
    left:
      - href: index.qmd
        text: About

      - href: projects.qmd
        text: Projects

      - href: teaching.qmd
        text: Teaching

      - href: pd.qmd
        text: Professional Development

      - href: publications.qmd
        text: Publications

      - href: talks.qmd
        text: Talks

      - href: CV.pdf
        text: CV


format:
  html:
    page-layout: full
    theme: [darkly, styles.scss]
    toc: true
