project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Welcome!"

  page-footer:
    left: "&copy; Copyright 2022, Elijah Meyer"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    background: "#2af0f7" # Teal
  navbar:
    background: "#2af0f7" # Teal
    foreground: "light"
    pinned: true
    left:
      - href: index.qmd
        text: About

      - href: projects/index.qmd
        text: Current Projects

      - href: teaching/teaching.qmd
        text: Teaching

      - href: PD/PD.qmd
        text: Professional Development

      - href: publications/publications.qmd
        text: Publications

      - href: talks/talks.qmd
        text: Talks

      - href: cv/cv.qmd
        text: CV


format:
  html:
    page-layout: full
    theme: darkly
    css: styles.css
    toc: true




