---
title: "Professional Development"
---

Below is an overview of the professional development (PD) programs I have helped develop, organize, and/or run.

## TA Training 

Duke Statistical Science, Spring 2024

Created, developed and facilitated Duke's first workshops to help prepare teaching assistants in the following areas of teaching: using active learning, Quarto, grading & giving student feedback; and GitHub. Workshops were 1.5 hours and conducted via Zoom. 

Workshop 1 - Active Learning: [Slides](https://elijahmeyer3.github.io/199-training/workshop1/teaching/teaching_slides.html#/title-slide)

Workshop 1 - Quarto: [Slides](https://elijahmeyer3.github.io/199-training/workshop1/quarto/quarto-slides.html#/title-slide); [Activity](https://github.com/ElijahMeyer3/quarto-training-exercises)

Workshop 2 - Grading & Student Feedback: [Slides](https://elijahmeyer3.github.io/199-training/workshop2/workshop2-slides.html#/title-slide); [Activity](https://github.com/ElijahMeyer3/grading-training-exercise)

Workshop 2 - GitHub: [Slides](https://elijahmeyer3.github.io/199-training/workshop2/workshop2-slides.html#/github)



## Head TA Training

Duke Statistical Science, Spring 2023

Redesigned and updated training preparation materials for TAs in leadership positions in the statistical sciences department at Duke. Co-lead training meeting to prepare TAs on their administrative and teaching responsibilities.

Collaboration with [Dr. Joan Durso](https://scholars.duke.edu/person/joan.combs.durso) and [Dr. Mine Çetinkaya-Rundel](https://mine-cr.com/).


## Excellence in Teaching Symposium

Montana State University, Fall 2017 and Spring 2018

Redesigned and led year-long teaching program for new graduate students. Organized and executed weekly hour-long teaching symposiums, such as Responding to Student Contributions in the Classroom. Mentored new graduate students on how to effectively communicate mathematical and statistical concepts to diverse learners.

Collaboration with [Dr. Jennifer Green](https://directory.natsci.msu.edu/Directory/Profiles/Person/102588?org=2&group=152) and [Dr. Liz Arnold](https://mathematics.colostate.edu/person/?id=B1577B723415D27B13D66791298FF26F&sq=t).
